language: java

#env:
#  - RAILS_ENV=test

services:
  - mysql

#addons:
#  apt:
#    sources:
#      - mysql-5.7-trusty
#    packages:
#      - mysql-server
#      - mysql-client

#before_install:
#  - bash .travis.install-mysql-5.7
#  - gem update --system 2.6.11
#  - gem update bundler

#install:
#  - bundle install --path vendor/bundle
#  - npm install

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS inscripcion;' #@MartinCastello
  - mysql -e 'CREATE DATABASE inscripcion;'
  - mysql -e 'use inscripcion;'
#  - mysql -e "USE mysql;
#  - mysql -e 'USE mysql;' #Se comenta porque para crear la tabla usuario necesita database instripcion
#      DROP TABLE IF EXISTS usuario;
#  - mysql -e 'DROP TABLE IF EXISTS usuario;' #Se comenta porque falla en travis.
#  CREATE TABLE IF NOT EXISTS `usuario` (
#    `id` int(11) NOT NULL AUTO_INCREMENT,
#    `nombre` varchar(50) DEFAULT NULL,
#    `apellido` varchar(50) DEFAULT NULL,
#    `legajo` varchar(50) DEFAULT NULL,
#    PRIMARY KEY (`id`)
#  ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;"

#  - mysql -e 'CREATE TABLE usuario (id int(11) NOT NULL AUTO_INCREMENT, apellido varchar(50) DEFAULT NULL, legajo varchar(50) DEFAULT NULL, PRIMARY KEY (id), ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3;'
#Se comento lo de arriba por error en travis, entonces llamo a archivo usuario.sql
  - mysql -u root inscripcion < src/main/resources/database/alumno.sql
  - mysql -u root inscripcion < src/main/resources/database/cursadas.sql
  - mysql -u root inscripcion < src/main/resources/database/inscripciones.sql
  - mysql -u root inscripcion < src/main/resources/database/materia.sql
  - mysql -u root inscripcion < src/main/resources/database/profesor.sql
  - mysql -u root inscripcion < src/main/resources/database/historial.sql
  - mysql -u root inscripcion < src/main/resources/database/correlativas.sql

#  - mysql -utravis < src/main/resources/database/schema_creation.sql
#  - mysql -utravis < src/main/resources/database/user.sql
#  - cp ./.travis.database.yml ./config/database.yml
#  - chmod +x /usr/bin/env sh

#script:
#  - bundle exec rake db:schema:load
#  - bundle exec rake db:create

#  - bundle exec rake db:test:prepare
#  - bundle exec rake spec

#script:
#  - RAILS_ENV=test bundle exec rake db:create
#  - RAILS_ENV=test bundle exec rake db:migrate
#  - /usr/bin/env sh


#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/

#after_failure:
#  - "mysql -e 'show databases;'"
#  - "cat ./config/database.yml"
#  - "echo $RAILS_ENV"
#  - "bundle exec rake --version"
