source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gems.github.com"

gem "acts_as_reportable", "1.1.1"
gem "attr_encrypted", "1.1.2"
gem "cucumber", "0.4.3"
gem "builder", "2.1.2"
gem "email_spec", "0.6.2"
gem "fakeweb", "1.3.0"
gem "ftpfxp", "0.0.4"
gem "geokit", "1.5.0"
gem "googlecharts", "1.3.6", :require => "gchart"
gem "haml", "2.2.17"
gem "hoe", "2.6.1"
gem "httparty", "0.4.3"
gem "mechanize", "0.6.7"
gem "mocha", "0.9.9"
gem "mongrel", "1.0.1"
gem "newrelic_rpm", "2.9.8"
gem "nokogiri", "1.4.2"
gem "polyglot", "0.2.9"
gem "prawn", "0.2.2"
gem "rake", "0.8.7"
gem "RedCloth", "3.0.3", :require => "redcloth"
gem "rghost", "0.8.7.6"
gem "rghost_barcode", "0.9"
gem "rspec", "1.2.9", :require => "spec"
gem "rspec-rails", "1.2.9", :require => false
gem "rubyist-aasm", "2.1.1", :require => "aasm"
gem "ruby-hl7", "1.0.3"
gem "scruffy", "0.2.6"
gem "termios", "0.9.4"
gem "thoughtbot-factory_girl", "1.2.2", :require => "factory_girl"
gem "thoughtbot-shoulda", "2.11.1", :require => "shoulda"
gem "webrat", "0.5.3"

# Travis specific
gem "activerecord-mysql2-adapter"